// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_SMPS_SCREEN.h"
#include "ui_HOME_SCREEN.h"
#include "ui_INVERTERSCREEN.h"
#include "ui_CCU_SCREEN.h"
#include "ui_AC_CONTROLER_SCREEN_.h"
#include "ui_Screen2.h"
#include "ui_DC_CONTROLER_SCREEN.h"
#include "ui_LIFO_BATTERY_SCREEN.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_smpslogo800x400_png);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
