// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_ractive_energy_value;
lv_obj_t * uic_energyconsup_value;
lv_obj_t * uic_frequencyvalue;
lv_obj_t * uic_ac_currentvalue;
lv_obj_t * uic_ac_voltage_value;
lv_obj_t * uic_power_fac_value;
lv_obj_t * uic_reactivepower_value;
lv_obj_t * uic_activepowervalue;
lv_obj_t * uic_AC_CONTROLER_SCREEN_;
lv_obj_t * ui_AC_CONTROLER_SCREEN_ = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_activepowervalue = NULL;
lv_obj_t * ui_reactivepower_value = NULL;
lv_obj_t * ui_power_fac_value = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_ac_voltage_value = NULL;
lv_obj_t * ui_ac_currentvalue = NULL;
lv_obj_t * ui_frequencyvalue = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_energyconsup_value = NULL;
lv_obj_t * ui_ractive_energy_value = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions
void ui_event_activepowervalue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_activepowervalue(e);
    }
}

void ui_event_reactivepower_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_reactivepower_value(e);
    }
}

void ui_event_power_fac_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_power_fac_value(e);
    }
}

void ui_event_Label26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_basic_set_property(ui_Label26, _UI_BASIC_PROPERTY_POSITION_X,  0);
    }
}

void ui_event_ac_voltage_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_voltage_value(e);
    }
}

void ui_event_ac_currentvalue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_currentvalue(e);
    }
}

void ui_event_frequencyvalue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_frequencyvalue(e);
    }
}

void ui_event_energyconsup_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_energyconsup_value(e);
    }
}

void ui_event_ractive_energy_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ac_ractive_energy_value(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_HOME_SCREEN_screen_init);
    }
}

// build funtions

void ui_AC_CONTROLER_SCREEN__screen_init(void)
{
    ui_AC_CONTROLER_SCREEN_ = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AC_CONTROLER_SCREEN_,
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_AC_CONTROLER_SCREEN_, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_AC_CONTROLER_SCREEN_, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_AC_CONTROLER_SCREEN_, lv_color_hex(0x633A03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AC_CONTROLER_SCREEN_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AC_CONTROLER_SCREEN_, lv_color_hex(0x614926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AC_CONTROLER_SCREEN_, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_AC_CONTROLER_SCREEN_);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 325);
    lv_obj_set_height(ui_Container3, 400);
    lv_obj_set_x(ui_Container3, 132);
    lv_obj_set_y(ui_Container3, -21);
    lv_obj_set_align(ui_Container3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_state(ui_Container3, LV_STATE_FOCUSED);       /// States
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Container3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x9C8054), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel1, 308);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -174);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Power Parameters");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Reactive Power (kVAR)");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 1);
    lv_obj_set_y(ui_Label29, 108);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Power Factor (PF)");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -1);
    lv_obj_set_y(ui_Label30, -109);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Active Power (kW)");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_activepowervalue = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_activepowervalue, 290);
    lv_obj_set_height(ui_activepowervalue, 46);
    lv_obj_set_x(ui_activepowervalue, 4);
    lv_obj_set_y(ui_activepowervalue, -70);
    lv_obj_set_align(ui_activepowervalue, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_activepowervalue, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_activepowervalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_activepowervalue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_activepowervalue, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_activepowervalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_activepowervalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reactivepower_value = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_reactivepower_value, 290);
    lv_obj_set_height(ui_reactivepower_value, 46);
    lv_obj_set_x(ui_reactivepower_value, 7);
    lv_obj_set_y(ui_reactivepower_value, 43);
    lv_obj_set_align(ui_reactivepower_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_reactivepower_value, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_reactivepower_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_reactivepower_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_reactivepower_value, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_reactivepower_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_reactivepower_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_fac_value = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_power_fac_value, 290);
    lv_obj_set_height(ui_power_fac_value, 46);
    lv_obj_set_x(ui_power_fac_value, 5);
    lv_obj_set_y(ui_power_fac_value, 147);
    lv_obj_set_align(ui_power_fac_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_power_fac_value, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_power_fac_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_power_fac_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_power_fac_value, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_power_fac_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_power_fac_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_AC_CONTROLER_SCREEN_);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 326);
    lv_obj_set_height(ui_Container2, 400);
    lv_obj_set_x(ui_Container2, 487);
    lv_obj_set_y(ui_Container2, -21);
    lv_obj_set_align(ui_Container2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x9C8054), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel3, 308);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, -1);
    lv_obj_set_y(ui_Panel3, -174);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Basic Electric");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "AC Current (A RMS)");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 1);
    lv_obj_set_y(ui_Label25, 108);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Frequency (Hz)");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -1);
    lv_obj_set_y(ui_Label26, -109);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "AC Voltage (V RMS)");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ac_voltage_value = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_ac_voltage_value, 290);
    lv_obj_set_height(ui_ac_voltage_value, 46);
    lv_obj_set_x(ui_ac_voltage_value, -3);
    lv_obj_set_y(ui_ac_voltage_value, -65);
    lv_obj_set_align(ui_ac_voltage_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_ac_voltage_value, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ac_voltage_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ac_voltage_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ac_voltage_value, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ac_voltage_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ac_voltage_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ac_currentvalue = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_ac_currentvalue, 290);
    lv_obj_set_height(ui_ac_currentvalue, 46);
    lv_obj_set_x(ui_ac_currentvalue, 1);
    lv_obj_set_y(ui_ac_currentvalue, 40);
    lv_obj_set_align(ui_ac_currentvalue, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_ac_currentvalue, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ac_currentvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ac_currentvalue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ac_currentvalue, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ac_currentvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ac_currentvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_frequencyvalue = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_frequencyvalue, 290);
    lv_obj_set_height(ui_frequencyvalue, 46);
    lv_obj_set_x(ui_frequencyvalue, 4);
    lv_obj_set_y(ui_frequencyvalue, 150);
    lv_obj_set_align(ui_frequencyvalue, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_frequencyvalue, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_frequencyvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_frequencyvalue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_frequencyvalue, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_frequencyvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_frequencyvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_AC_CONTROLER_SCREEN_);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 325);
    lv_obj_set_height(ui_Container4, 400);
    lv_obj_set_x(ui_Container4, -220);
    lv_obj_set_y(ui_Container4, -21);
    lv_obj_set_align(ui_Container4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Container4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x9C8054), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel2, 308);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, -174);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Energy Parameters");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Reactive Energy (kVARh)");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -1);
    lv_obj_set_y(ui_Label34, -109);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Energy Consumption (kWh)");
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_energyconsup_value = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_energyconsup_value, 290);
    lv_obj_set_height(ui_energyconsup_value, 46);
    lv_obj_set_x(ui_energyconsup_value, -3);
    lv_obj_set_y(ui_energyconsup_value, -65);
    lv_obj_set_align(ui_energyconsup_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_energyconsup_value, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_energyconsup_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_energyconsup_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_energyconsup_value, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_energyconsup_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_energyconsup_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ractive_energy_value = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_ractive_energy_value, 290);
    lv_obj_set_height(ui_ractive_energy_value, 46);
    lv_obj_set_x(ui_ractive_energy_value, -2);
    lv_obj_set_y(ui_ractive_energy_value, 44);
    lv_obj_set_align(ui_ractive_energy_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_ractive_energy_value, lv_color_hex(0x000500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ractive_energy_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ractive_energy_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ractive_energy_value, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ractive_energy_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ractive_energy_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_AC_CONTROLER_SCREEN_);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 711);
    lv_obj_set_height(ui_Container14, 42);
    lv_obj_set_x(ui_Container14, 14);
    lv_obj_set_y(ui_Container14, -211);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 26);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "AC CONTROLLER ");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x070000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_AC_CONTROLER_SCREEN_);
    lv_obj_set_width(ui_Button8, 110);
    lv_obj_set_height(ui_Button8, 40);
    lv_obj_set_x(ui_Button8, -333);
    lv_obj_set_y(ui_Button8, 203);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Back");

    lv_obj_add_event_cb(ui_activepowervalue, ui_event_activepowervalue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_reactivepower_value, ui_event_reactivepower_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_power_fac_value, ui_event_power_fac_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label26, ui_event_Label26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ac_voltage_value, ui_event_ac_voltage_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ac_currentvalue, ui_event_ac_currentvalue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_frequencyvalue, ui_event_frequencyvalue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_energyconsup_value, ui_event_energyconsup_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ractive_energy_value, ui_event_ractive_energy_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    uic_AC_CONTROLER_SCREEN_ = ui_AC_CONTROLER_SCREEN_;
    uic_activepowervalue = ui_activepowervalue;
    uic_reactivepower_value = ui_reactivepower_value;
    uic_power_fac_value = ui_power_fac_value;
    uic_ac_voltage_value = ui_ac_voltage_value;
    uic_ac_currentvalue = ui_ac_currentvalue;
    uic_frequencyvalue = ui_frequencyvalue;
    uic_energyconsup_value = ui_energyconsup_value;
    uic_ractive_energy_value = ui_ractive_energy_value;

}

void ui_AC_CONTROLER_SCREEN__screen_destroy(void)
{
    if(ui_AC_CONTROLER_SCREEN_) lv_obj_del(ui_AC_CONTROLER_SCREEN_);

    // NULL screen variables
    uic_AC_CONTROLER_SCREEN_ = NULL;
    ui_AC_CONTROLER_SCREEN_ = NULL;
    ui_Container3 = NULL;
    ui_Panel1 = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;
    ui_Label30 = NULL;
    uic_activepowervalue = NULL;
    ui_activepowervalue = NULL;
    uic_reactivepower_value = NULL;
    ui_reactivepower_value = NULL;
    uic_power_fac_value = NULL;
    ui_power_fac_value = NULL;
    ui_Container2 = NULL;
    ui_Panel3 = NULL;
    ui_Label11 = NULL;
    ui_Label14 = NULL;
    ui_Label25 = NULL;
    ui_Label26 = NULL;
    uic_ac_voltage_value = NULL;
    ui_ac_voltage_value = NULL;
    uic_ac_currentvalue = NULL;
    ui_ac_currentvalue = NULL;
    uic_frequencyvalue = NULL;
    ui_frequencyvalue = NULL;
    ui_Container4 = NULL;
    ui_Panel2 = NULL;
    ui_Label31 = NULL;
    ui_Label32 = NULL;
    ui_Label34 = NULL;
    uic_energyconsup_value = NULL;
    ui_energyconsup_value = NULL;
    uic_ractive_energy_value = NULL;
    ui_ractive_energy_value = NULL;
    ui_Container14 = NULL;
    ui_Label13 = NULL;
    ui_Button8 = NULL;
    ui_Label16 = NULL;

}
