// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_AC_CONTROLER_SCREEN__H
#define UI_AC_CONTROLER_SCREEN__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AC_CONTROLER_SCREEN_
extern void ui_AC_CONTROLER_SCREEN__screen_init(void);
extern void ui_AC_CONTROLER_SCREEN__screen_destroy(void);
extern lv_obj_t * ui_AC_CONTROLER_SCREEN_;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern void ui_event_activepowervalue(lv_event_t * e);
extern lv_obj_t * ui_activepowervalue;
extern void ui_event_reactivepower_value(lv_event_t * e);
extern lv_obj_t * ui_reactivepower_value;
extern void ui_event_power_fac_value(lv_event_t * e);
extern lv_obj_t * ui_power_fac_value;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label25;
extern void ui_event_Label26(lv_event_t * e);
extern lv_obj_t * ui_Label26;
extern void ui_event_ac_voltage_value(lv_event_t * e);
extern lv_obj_t * ui_ac_voltage_value;
extern void ui_event_ac_currentvalue(lv_event_t * e);
extern lv_obj_t * ui_ac_currentvalue;
extern void ui_event_frequencyvalue(lv_event_t * e);
extern lv_obj_t * ui_frequencyvalue;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label34;
extern void ui_event_energyconsup_value(lv_event_t * e);
extern lv_obj_t * ui_energyconsup_value;
extern void ui_event_ractive_energy_value(lv_event_t * e);
extern lv_obj_t * ui_ractive_energy_value;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label13;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES
extern lv_obj_t * uic_AC_CONTROLER_SCREEN_;
extern lv_obj_t * uic_activepowervalue;
extern lv_obj_t * uic_reactivepower_value;
extern lv_obj_t * uic_power_fac_value;
extern lv_obj_t * uic_ac_voltage_value;
extern lv_obj_t * uic_ac_currentvalue;
extern lv_obj_t * uic_frequencyvalue;
extern lv_obj_t * uic_energyconsup_value;
extern lv_obj_t * uic_ractive_energy_value;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

