// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CCU_SCREEN_H
#define UI_CCU_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CCU_SCREEN
extern void ui_CCU_SCREEN_screen_init(void);
extern void ui_CCU_SCREEN_screen_destroy(void);
extern lv_obj_t * ui_CCU_SCREEN;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Container6;
extern void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
extern void ui_event_Label40(lv_event_t * e);
extern lv_obj_t * ui_Label40;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label41;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CCU_SCREEN;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

