// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "modbus.h"

lv_obj_t * uic_CCU_SCREEN;
lv_obj_t * ui_CCU_SCREEN = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Label41 = NULL;

// ---------------------------------------------------------------
// CCU Roller Parameter Index (must match lv_roller_set_options order)
// ---------------------------------------------------------------
typedef enum {
    CCU_PARAM_BATTERY_VOLTAGE        = 0,   // Battery Voltage (V)
    CCU_PARAM_BATTERY_CHARGE_CURRENT = 1,   // Battery Charging Current (A)
    CCU_PARAM_BATTERY_SOC            = 2,   // Battery State of Charge (SOC) (%)
    CCU_PARAM_BATTERY_TEMP           = 3,   // Battery Temperature (°C)
    CCU_PARAM_BATTERY_CHARGE_MODE    = 4,   // Battery Charging Mode
    CCU_PARAM_PV_INPUT_VOLTAGE       = 5,   // PV Input Voltage (V)
    CCU_PARAM_PV_INPUT_CURRENT       = 6,   // PV Input Current (A)
    CCU_PARAM_PV_INPUT_POWER         = 7,   // PV Input Power (W)
    CCU_PARAM_MPPT_STATUS            = 8,   // MPPT Tracking Status
    CCU_PARAM_CC_OUTPUT_CURRENT      = 9,   // Charge Controller Output Current (A)
    CCU_PARAM_OVP_STATUS             = 10,  // Overvoltage Protection Status
    CCU_PARAM_OCP_STATUS             = 11,  // Overcurrent / Short Circuit Status
    CCU_PARAM_COUNT                  = 12
} CCU_ParamIndex_t;

// ---------------------------------------------------------------
// Dummy values — one per parameter (replace with real sensor reads later)
// ---------------------------------------------------------------
char ccu_values[CCU_PARAM_COUNT][20] = {
    [CCU_PARAM_BATTERY_VOLTAGE]        = "48.72",   // V
    [CCU_PARAM_BATTERY_CHARGE_CURRENT] = "12.35",   // A
    [CCU_PARAM_BATTERY_SOC]            = "83.50",   // %
    [CCU_PARAM_BATTERY_TEMP]           = "36.20",   // °C
    [CCU_PARAM_BATTERY_CHARGE_MODE]    = "MPPT",    // mode string
    [CCU_PARAM_PV_INPUT_VOLTAGE]       = "36.80",   // V
    [CCU_PARAM_PV_INPUT_CURRENT]       = "5.42",    // A
    [CCU_PARAM_PV_INPUT_POWER]         = "199.30",  // W
    [CCU_PARAM_MPPT_STATUS]            = "Active",  // status string
    [CCU_PARAM_CC_OUTPUT_CURRENT]      = "10.15",    //A
    [CCU_PARAM_OVP_STATUS]             = "Normal",   //status string
    [CCU_PARAM_OCP_STATUS]             = "Normal",   //status string
};

// ---------------------------------------------------------------
// Helper: update ui_Label40 based on the currently selected roller item
// ---------------------------------------------------------------
static void ccu_update_display(void)
{
    uint16_t selected = lv_roller_get_selected(ui_Roller1);
    if(selected < CCU_PARAM_COUNT) {
        lv_label_set_text(ui_Label40, ccu_values[selected]);
    }
}

// ---------------------------------------------------------------
// Event functions
// ---------------------------------------------------------------
void ui_event_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        // Read which item the user just scrolled to and show its dummy value
        ccu_update_display();
    }
}

void ui_event_Label40(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        MPPTTrackingStatus(e);
        ChargeControllerOutputCurrent(e);
        PVInputPower(e);
        PVInputCurrent(e);
        PVInputVoltage(e);
        BatteryChargingMode(e);
        BatteryTemperature(e);
        BatteryStateofCharge(e);
        BatteryChargingCurrent(e);
        BatteryVoltage(e);
        OvervoltageProtectionStatus(e);
        OvercurrentShortCircuitStatus(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_HOME_SCREEN_screen_init);
    }
}

// ---------------------------------------------------------------
// Build function
// ---------------------------------------------------------------
void ui_CCU_SCREEN_screen_init(void)
{
    ui_CCU_SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CCU_SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CCU_SCREEN, lv_color_hex(0x9FD9BC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CCU_SCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CCU_SCREEN, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CCU_SCREEN, lv_color_hex(0xFAF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CCU_SCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_CCU_SCREEN);
    lv_obj_set_width(ui_Label39, 595);
    lv_obj_set_height(ui_Label39, 58);
    lv_obj_set_x(ui_Label39, lv_pct(0));
    lv_obj_set_y(ui_Label39, lv_pct(-42));
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "     Charge Control Unit ");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x0B0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_CCU_SCREEN);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 689);
    lv_obj_set_height(ui_Container6, 313);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 3);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0x0B0E2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Container6);
    lv_roller_set_options(ui_Roller1,
                          "Battery Voltage (V)\nBattery Charging Current (A)\nBattery State of Charge (SOC) (%)\nBattery Temperature (\xc2\xb0""C)\nBattery Charging Mode\nPV Input Voltage (V)\nPV Input Current (A)\nPV Input Power (W)\nMPPT Tracking Status\nCharge Controller Output Current (A)\nOvervoltage Protection Status\nOvercurrent / Short Circuit Status",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Roller1, 0, LV_ANIM_OFF);   // start at index 0
    lv_obj_set_width(ui_Roller1, 244);
    lv_obj_set_height(ui_Roller1, 243);
    lv_obj_set_x(ui_Roller1, -190);
    lv_obj_set_y(ui_Roller1, -6);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0x060101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x08B2F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label40, 233);
    lv_obj_set_height(ui_Label40, 127);
    lv_obj_set_x(ui_Label40, 143);
    lv_obj_set_y(ui_Label40, -93);
    lv_obj_set_align(ui_Label40, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0x0BF215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label40, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label40, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label40, lv_color_hex(0xF9F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label40, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label40, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label40, lv_color_hex(0xF7F1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Show the dummy value for the first item immediately on screen load
    _ui_label_set_property(ui_Label40, _UI_LABEL_PROPERTY_TEXT,
                           ccu_values[CCU_PARAM_BATTERY_VOLTAGE]);

    ui_Button9 = lv_btn_create(ui_CCU_SCREEN);
    lv_obj_set_width(ui_Button9, 120);
    lv_obj_set_height(ui_Button9, 45);
    lv_obj_set_x(ui_Button9, -324);
    lv_obj_set_y(ui_Button9, 199);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Back");
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Roller1, ui_event_Roller1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label40, ui_event_Label40, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    uic_CCU_SCREEN = ui_CCU_SCREEN;
}

void ui_CCU_SCREEN_screen_destroy(void)
{
    if(ui_CCU_SCREEN) lv_obj_del(ui_CCU_SCREEN);

    // NULL screen variables
    uic_CCU_SCREEN = NULL;
    ui_CCU_SCREEN  = NULL;
    ui_Label39     = NULL;
    ui_Container6  = NULL;
    ui_Roller1     = NULL;
    ui_Label40     = NULL;
    ui_Button9     = NULL;
    ui_Label41     = NULL;
}