// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_voltagevalue;
lv_obj_t * uic_powervalue;
lv_obj_t * uic_currentvalue;
lv_obj_t * uic_frequency__value;
lv_obj_t * uic_DC_CONTROLER_SCREEN;
lv_obj_t * ui_DC_CONTROLER_SCREEN = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Label60 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label63 = NULL;
lv_obj_t * ui_frequency__value = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_Label65 = NULL;
lv_obj_t * ui_currentvalue = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Label66 = NULL;
lv_obj_t * ui_powervalue = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Label61 = NULL;
lv_obj_t * ui_voltagevalue = NULL;
// event funtions
void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HOME_SCREEN_screen_init);
    }
}

void ui_event_frequency__value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dc_frequency__value(e);
    }
}

void ui_event_currentvalue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dc_currentvalue(e);
    }
}

void ui_event_powervalue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dc_powervalue(e);
    }
}

void ui_event_voltagevalue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dc_voltagevalue(e);
    }
}

// build funtions

void ui_DC_CONTROLER_SCREEN_screen_init(void)
{
    ui_DC_CONTROLER_SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DC_CONTROLER_SCREEN,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_DC_CONTROLER_SCREEN, lv_color_hex(0xDF8A8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DC_CONTROLER_SCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_DC_CONTROLER_SCREEN, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_DC_CONTROLER_SCREEN);
    lv_obj_set_width(ui_Label59, 355);
    lv_obj_set_height(ui_Label59, 59);
    lv_obj_set_x(ui_Label59, -1);
    lv_obj_set_y(ui_Label59, -199);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "DC Controller ");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x090101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_DC_CONTROLER_SCREEN);
    lv_obj_set_width(ui_Button12, 111);
    lv_obj_set_height(ui_Button12, 38);
    lv_obj_set_x(ui_Button12, -323);
    lv_obj_set_y(ui_Button12, 201);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label60 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "Back");
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_DC_CONTROLER_SCREEN);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 344);
    lv_obj_set_height(ui_Container10, 54);
    lv_obj_set_x(ui_Container10, 212);
    lv_obj_set_y(ui_Container10, -129);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label63 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label63, 154);
    lv_obj_set_height(ui_Label63, 30);
    lv_obj_set_x(ui_Label63, -94);
    lv_obj_set_y(ui_Label63, 0);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "frequency  :");
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_frequency__value = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_frequency__value, 150);
    lv_obj_set_height(ui_frequency__value, 40);
    lv_obj_set_x(ui_frequency__value, 49);
    lv_obj_set_y(ui_frequency__value, 0);
    lv_obj_set_align(ui_frequency__value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_frequency__value, lv_color_hex(0x16F905), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_frequency__value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_frequency__value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_frequency__value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_DC_CONTROLER_SCREEN);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 299);
    lv_obj_set_height(ui_Container12, 54);
    lv_obj_set_x(ui_Container12, -212);
    lv_obj_set_y(ui_Container12, -14);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label65 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, -94);
    lv_obj_set_y(ui_Label65, 0);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "current  :");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentvalue = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_currentvalue, 150);
    lv_obj_set_height(ui_currentvalue, 40);
    lv_obj_set_x(ui_currentvalue, 43);
    lv_obj_set_y(ui_currentvalue, 0);
    lv_obj_set_align(ui_currentvalue, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_currentvalue, lv_color_hex(0x22FA05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_currentvalue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_currentvalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_DC_CONTROLER_SCREEN);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 344);
    lv_obj_set_height(ui_Container13, 54);
    lv_obj_set_x(ui_Container13, 200);
    lv_obj_set_y(ui_Container13, -23);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label66 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, -94);
    lv_obj_set_y(ui_Label66, 0);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "power  :");
    lv_obj_set_style_text_color(ui_Label66, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label66, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label66, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powervalue = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_powervalue, 150);
    lv_obj_set_height(ui_powervalue, 40);
    lv_obj_set_x(ui_powervalue, 77);
    lv_obj_set_y(ui_powervalue, -2);
    lv_obj_set_align(ui_powervalue, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_powervalue, lv_color_hex(0x15F709), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_powervalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_powervalue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powervalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_DC_CONTROLER_SCREEN);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 299);
    lv_obj_set_height(ui_Container9, 54);
    lv_obj_set_x(ui_Container9, -215);
    lv_obj_set_y(ui_Container9, -135);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label61 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, -94);
    lv_obj_set_y(ui_Label61, 0);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "voltage  :");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltagevalue = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_voltagevalue, 150);
    lv_obj_set_height(ui_voltagevalue, 40);
    lv_obj_set_x(ui_voltagevalue, 43);
    lv_obj_set_y(ui_voltagevalue, 2);
    lv_obj_set_align(ui_voltagevalue, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_voltagevalue, lv_color_hex(0x3BF20A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltagevalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_voltagevalue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltagevalue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_frequency__value, ui_event_frequency__value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_currentvalue, ui_event_currentvalue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_powervalue, ui_event_powervalue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_voltagevalue, ui_event_voltagevalue, LV_EVENT_ALL, NULL);
    uic_DC_CONTROLER_SCREEN = ui_DC_CONTROLER_SCREEN;
    uic_frequency__value = ui_frequency__value;
    uic_currentvalue = ui_currentvalue;
    uic_powervalue = ui_powervalue;
    uic_voltagevalue = ui_voltagevalue;

}

void ui_DC_CONTROLER_SCREEN_screen_destroy(void)
{
    if(ui_DC_CONTROLER_SCREEN) lv_obj_del(ui_DC_CONTROLER_SCREEN);

    // NULL screen variables
    uic_DC_CONTROLER_SCREEN = NULL;
    ui_DC_CONTROLER_SCREEN = NULL;
    ui_Label59 = NULL;
    ui_Button12 = NULL;
    ui_Label60 = NULL;
    ui_Container10 = NULL;
    ui_Label63 = NULL;
    uic_frequency__value = NULL;
    ui_frequency__value = NULL;
    ui_Container12 = NULL;
    ui_Label65 = NULL;
    uic_currentvalue = NULL;
    ui_currentvalue = NULL;
    ui_Container13 = NULL;
    ui_Label66 = NULL;
    uic_powervalue = NULL;
    ui_powervalue = NULL;
    ui_Container9 = NULL;
    ui_Label61 = NULL;
    uic_voltagevalue = NULL;
    ui_voltagevalue = NULL;

}
