// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DC_CONTROLER_SCREEN_H
#define UI_DC_CONTROLER_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DC_CONTROLER_SCREEN
extern void ui_DC_CONTROLER_SCREEN_screen_init(void);
extern void ui_DC_CONTROLER_SCREEN_screen_destroy(void);
extern lv_obj_t * ui_DC_CONTROLER_SCREEN;
extern lv_obj_t * ui_Label59;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label63;
extern void ui_event_frequency__value(lv_event_t * e);
extern lv_obj_t * ui_frequency__value;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label65;
extern void ui_event_currentvalue(lv_event_t * e);
extern lv_obj_t * ui_currentvalue;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label66;
extern void ui_event_powervalue(lv_event_t * e);
extern lv_obj_t * ui_powervalue;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label61;
extern void ui_event_voltagevalue(lv_event_t * e);
extern lv_obj_t * ui_voltagevalue;
// CUSTOM VARIABLES
extern lv_obj_t * uic_DC_CONTROLER_SCREEN;
extern lv_obj_t * uic_frequency__value;
extern lv_obj_t * uic_currentvalue;
extern lv_obj_t * uic_powervalue;
extern lv_obj_t * uic_voltagevalue;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

