// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

#include "ev_data.h"
#include <string.h>   // for strcpy

void time_value(lv_event_t * e)
{
	// Your code here
}

void date_value(lv_event_t * e)
{
	// Your code here
}

void day_value(lv_event_t * e)
{
	// Your code here
}

void invertervoltage_value(lv_event_t * e)
{
	// Your code here
}

void invertersoc_vlaue(lv_event_t * e)
{
	// Your code here
}

void invertersoh_value(lv_event_t * e)
{
	// Your code here
}

void inverterfreq_value(lv_event_t * e)
{
	// Your code here
}

void inverterpower_value(lv_event_t * e)
{
	// Your code here
}

void invertercurrent_value(lv_event_t * e)
{
	// Your code here
}

void MPPTTrackingStatus(lv_event_t * e)
{
	// Your code here
}

void ChargeControllerOutputCurrent(lv_event_t * e)
{
	// Your code here
}

void PVInputPower(lv_event_t * e)
{
	// Your code here
}

void PVInputCurrent(lv_event_t * e)
{
	// Your code here
}

void PVInputVoltage(lv_event_t * e)
{
	// Your code here
}

void BatteryChargingMode(lv_event_t * e)
{
	// Your code here
}

void BatteryTemperature(lv_event_t * e)
{
	// Your code here
}

void BatteryStateofCharge(lv_event_t * e)
{
	// Your code here
}

void BatteryChargingCurrent(lv_event_t * e)
{
	// Your code here
}

void BatteryVoltage(lv_event_t * e)
{
	// Your code here
}

void OvervoltageProtectionStatus(lv_event_t * e)
{
	// Your code here
}

void OvercurrentShortCircuitStatus(lv_event_t * e)
{
	// Your code here
}

void ac_activepowervalue(lv_event_t * e)
{
	// Your code here
}

void ac_reactivepower_value(lv_event_t * e)
{
	// Your code here
}

void ac_power_fac_value(lv_event_t * e)
{
	// Your code here
}

void ac_voltage_value(lv_event_t * e)
{
	// Your code here
}

void ac_currentvalue(lv_event_t * e)
{
	// Your code here
}

void ac_frequencyvalue(lv_event_t * e)
{
	// Your code here
}

void ac_energyconsup_value(lv_event_t * e)
{
	// Your code here
}

void ac_ractive_energy_value(lv_event_t * e)
{
	// Your code here
}

void start_on(lv_event_t * e)
{
	// Your code here
}

void stop_off(lv_event_t * e)
{
	// Your code here
}

void dc_frequency__value(lv_event_t * e)
{
	// Your code here
}

void dc_currentvalue(lv_event_t * e)
{
	// Your code here
}

void dc_powervalue(lv_event_t * e)
{
	// Your code here
}

void dc_voltagevalue(lv_event_t * e)
{
	// Your code here
}

void lifo_voltage_value__(lv_event_t * e)
{
	// Your code here
}

void lifo_fault_value_(lv_event_t * e)
{
	// Your code here
}

void lifo_temp_value(lv_event_t * e)
{
	// Your code here
}

void lifo_soc_value__(lv_event_t * e)
{
	// Your code here
}

void lifo_current_value__(lv_event_t * e)
{
	// Your code here
}
void ev_powervalue(lv_event_t * e)
{
	// Your code here
}

void ev_timevalue(lv_event_t * e)
{
	// Your code here
}

void ui_event_ev_start_button(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        ev_data.is_charging = 1;
        ev_data.time_min = 0;

        strcpy(ev_data.status, "CHARGING");
    }
}

void ui_event_ev_stop_button(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED)
    {
        ev_data.is_charging = 0;

        strcpy(ev_data.status, "STOPPED");
    }
}
