// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void time_value(lv_event_t * e);
void date_value(lv_event_t * e);
void day_value(lv_event_t * e);
void invertervoltage_value(lv_event_t * e);
void invertersoc_vlaue(lv_event_t * e);
void invertersoh_value(lv_event_t * e);
void inverterfreq_value(lv_event_t * e);
void inverterpower_value(lv_event_t * e);
void invertercurrent_value(lv_event_t * e);
void MPPTTrackingStatus(lv_event_t * e);
void ChargeControllerOutputCurrent(lv_event_t * e);
void PVInputPower(lv_event_t * e);
void PVInputCurrent(lv_event_t * e);
void PVInputVoltage(lv_event_t * e);
void BatteryChargingMode(lv_event_t * e);
void BatteryTemperature(lv_event_t * e);
void BatteryStateofCharge(lv_event_t * e);
void BatteryChargingCurrent(lv_event_t * e);
void BatteryVoltage(lv_event_t * e);
void OvervoltageProtectionStatus(lv_event_t * e);
void OvercurrentShortCircuitStatus(lv_event_t * e);
void ac_activepowervalue(lv_event_t * e);
void ac_reactivepower_value(lv_event_t * e);
void ac_power_fac_value(lv_event_t * e);
void ac_voltage_value(lv_event_t * e);
void ac_currentvalue(lv_event_t * e);
void ac_frequencyvalue(lv_event_t * e);
void ac_energyconsup_value(lv_event_t * e);
void ac_ractive_energy_value(lv_event_t * e);
void stop_off(lv_event_t * e);
void start_on(lv_event_t * e);
void dc_frequency__value(lv_event_t * e);
void dc_currentvalue(lv_event_t * e);
void dc_powervalue(lv_event_t * e);
void dc_voltagevalue(lv_event_t * e);
void lifo_voltage_value__(lv_event_t * e);
void lifo_fault_value_(lv_event_t * e);
void lifo_temp_value(lv_event_t * e);
void lifo_soc_value__(lv_event_t * e);
void lifo_current_value__(lv_event_t * e);
void ev_powervalue(lv_event_t * e);
void ev_timevalue(lv_event_t * e);
void ui_event_ev_start_button(lv_event_t * e);
void ui_event_ev_stop_button(lv_event_t * e);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
