// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_SCREEN_H
#define UI_HOME_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HOME_SCREEN
extern void ui_HOME_SCREEN_screen_init(void);
extern void ui_HOME_SCREEN_screen_destroy(void);
extern void ui_event_HOME_SCREEN(lv_event_t * e);
extern lv_obj_t * ui_HOME_SCREEN;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
extern void ui_event_TIME(lv_event_t * e);
extern lv_obj_t * ui_TIME;
extern void ui_event_DATE(lv_event_t * e);
extern lv_obj_t * ui_DATE;
extern void ui_event_DAY(lv_event_t * e);
extern lv_obj_t * ui_DAY;
// CUSTOM VARIABLES
extern lv_obj_t * uic_HOME_SCREEN;
extern lv_obj_t * uic_DATE;
extern lv_obj_t * uic_DAY;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

