// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_DAY;
lv_obj_t * uic_DATE;
lv_obj_t * uic_HOME_SCREEN;
lv_obj_t * ui_HOME_SCREEN = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_TIME = NULL;
lv_obj_t * ui_DATE = NULL;
lv_obj_t * ui_DAY = NULL;
// event funtions
void ui_event_HOME_SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SMPS_SCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SMPS_SCREEN_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_INVERTERSCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_INVERTERSCREEN_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_CCU_SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_CCU_SCREEN_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_LIFO_BATTERY_SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_LIFO_BATTERY_SCREEN_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_AC_CONTROLER_SCREEN_, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_AC_CONTROLER_SCREEN__screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_DC_CONTROLER_SCREEN, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_DC_CONTROLER_SCREEN_screen_init);
    }
}

void ui_event_TIME(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        time_value(e);
    }
}

void ui_event_DATE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        date_value(e);
    }
}

void ui_event_DAY(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        day_value(e);
    }
}

// build funtions

void ui_HOME_SCREEN_screen_init(void)
{
    ui_HOME_SCREEN = lv_obj_create(NULL);
    lv_obj_add_state(ui_HOME_SCREEN, LV_STATE_USER_1);       /// States
    lv_obj_clear_flag(ui_HOME_SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME_SCREEN, lv_color_hex(0x0F0319), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME_SCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HOME_SCREEN, lv_color_hex(0x1B0336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HOME_SCREEN, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_Button1, 235);
    lv_obj_set_height(ui_Button1, 85);
    lv_obj_set_x(ui_Button1, 242);
    lv_obj_set_y(ui_Button1, -50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button1, LV_STATE_FOCUSED);       /// States
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x6C8AC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x0C0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Button1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label4, 200);
    lv_obj_set_height(ui_Label4, 33);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "INVERTER");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x070000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_Button2, 235);
    lv_obj_set_height(ui_Button2, 85);
    lv_obj_set_x(ui_Button2, -235);
    lv_obj_set_y(ui_Button2, -47);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button2, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x6C8AC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button2, lv_color_hex(0x070000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label5, 200);
    lv_obj_set_height(ui_Label5, 73);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "CHARGE CONTROLLING UNIT");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_Button3, 235);
    lv_obj_set_height(ui_Button3, 85);
    lv_obj_set_x(ui_Button3, -236);
    lv_obj_set_y(ui_Button3, 54);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button3, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x6C8AC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label6, 192);
    lv_obj_set_height(ui_Label6, 29);
    lv_obj_set_x(ui_Label6, 2);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "EV CHARGER");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x050404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_Button4, 235);
    lv_obj_set_height(ui_Button4, 85);
    lv_obj_set_x(ui_Button4, -239);
    lv_obj_set_y(ui_Button4, 159);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button4, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x6C8AC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "LIFOPO4 BATTERY");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x060202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_Label1, 343);
    lv_obj_set_height(ui_Label1, 57);
    lv_obj_set_x(ui_Label1, 4);
    lv_obj_set_y(ui_Label1, -200);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "HOME ");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF3F7F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x3D4D69), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_Label1, lv_color_hex(0xF9FAFB), LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Button5 = lv_btn_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_Button5, 235);
    lv_obj_set_height(ui_Button5, 85);
    lv_obj_set_x(ui_Button5, 241);
    lv_obj_set_y(ui_Button5, 57);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x6C8AC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label8, 186);
    lv_obj_set_height(ui_Label8, 57);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "AC CONTROLLER ");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_Button6, 235);
    lv_obj_set_height(ui_Button6, 85);
    lv_obj_set_x(ui_Button6, 240);
    lv_obj_set_y(ui_Button6, 159);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x6C8AC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "DC CONTROLLER");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIME = lv_label_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_TIME, 192);
    lv_obj_set_height(ui_TIME, 46);
    lv_obj_set_x(ui_TIME, 284);
    lv_obj_set_y(ui_TIME, -198);
    lv_obj_set_align(ui_TIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TIME, "");
    lv_obj_set_style_text_color(ui_TIME, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TIME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TIME, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DATE = lv_label_create(ui_HOME_SCREEN);
    lv_obj_set_width(ui_DATE, 149);
    lv_obj_set_height(ui_DATE, 28);
    lv_obj_set_x(ui_DATE, -293);
    lv_obj_set_y(ui_DATE, -175);
    lv_obj_set_align(ui_DATE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DATE, "");
    lv_obj_set_style_text_color(ui_DATE, lv_color_hex(0xF7F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DATE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DATE, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DAY = lv_label_create(ui_HOME_SCREEN);
    lv_obj_set_height(ui_DAY, 27);
    lv_obj_set_width(ui_DAY, lv_pct(18));
    lv_obj_set_x(ui_DAY, -295);
    lv_obj_set_y(ui_DAY, -204);
    lv_obj_set_align(ui_DAY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DAY, "");
    lv_obj_set_style_text_color(ui_DAY, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DAY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DAY, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TIME, ui_event_TIME, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DATE, ui_event_DATE, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DAY, ui_event_DAY, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HOME_SCREEN, ui_event_HOME_SCREEN, LV_EVENT_ALL, NULL);
    uic_HOME_SCREEN = ui_HOME_SCREEN;
    uic_DATE = ui_DATE;
    uic_DAY = ui_DAY;

}

void ui_HOME_SCREEN_screen_destroy(void)
{
    if(ui_HOME_SCREEN) lv_obj_del(ui_HOME_SCREEN);

    // NULL screen variables
    uic_HOME_SCREEN = NULL;
    ui_HOME_SCREEN = NULL;
    ui_Button1 = NULL;
    ui_Label4 = NULL;
    ui_Button2 = NULL;
    ui_Label5 = NULL;
    ui_Button3 = NULL;
    ui_Label6 = NULL;
    ui_Button4 = NULL;
    ui_Label7 = NULL;
    ui_Label1 = NULL;
    ui_Button5 = NULL;
    ui_Label8 = NULL;
    ui_Button6 = NULL;
    ui_Label9 = NULL;
    ui_TIME = NULL;
    uic_DATE = NULL;
    ui_DATE = NULL;
    uic_DAY = NULL;
    ui_DAY = NULL;

}
