// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_current_value;
lv_obj_t * uic_power_value;
lv_obj_t * uic_frequency_value;
lv_obj_t * uic_SOH_value;
lv_obj_t * uic_SOC_value;
lv_obj_t * uic_voltage_value_;
lv_obj_t * uic_INVERTERSCREEN;
lv_obj_t * ui_INVERTERSCREEN = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_voltage_value_ = NULL;
lv_obj_t * ui_Spinner3 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_SOC_value = NULL;
lv_obj_t * ui_Spinner4 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_SOH_value = NULL;
lv_obj_t * ui_Spinner5 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_frequency_value = NULL;
lv_obj_t * ui_Spinner6 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_power_value = NULL;
lv_obj_t * ui_Spinner7 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_current_value = NULL;
// event funtions
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_HOME_SCREEN_screen_init);
    }
}

void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_HOME_SCREEN_screen_init);
    }
}

void ui_event_voltage_value_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        invertervoltage_value(e);
    }
}

void ui_event_SOC_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        invertersoc_vlaue(e);
    }
}

void ui_event_SOH_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        invertersoh_value(e);
    }
}

void ui_event_frequency_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        inverterfreq_value(e);
    }
}

void ui_event_power_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        inverterpower_value(e);
    }
}

void ui_event_current_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        invertercurrent_value(e);
    }
}

// build funtions

void ui_INVERTERSCREEN_screen_init(void)
{
    ui_INVERTERSCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_INVERTERSCREEN,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_INVERTERSCREEN, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_INVERTERSCREEN, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_INVERTERSCREEN, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_INVERTERSCREEN, lv_color_hex(0x081717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_INVERTERSCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_INVERTERSCREEN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_INVERTERSCREEN, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_INVERTERSCREEN, lv_color_hex(0x1E0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_INVERTERSCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_INVERTERSCREEN);
    lv_obj_set_width(ui_Label10, 500);
    lv_obj_set_height(ui_Label10, 52);
    lv_obj_set_x(ui_Label10, -5);
    lv_obj_set_y(ui_Label10, -204);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "INVERTER");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFBFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_INVERTERSCREEN);
    lv_obj_set_width(ui_Button7, 119);
    lv_obj_set_height(ui_Button7, 43);
    lv_obj_set_x(ui_Button7, -322);
    lv_obj_set_y(ui_Button7, 201);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Button7, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x716D6D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_Button7, lv_color_hex(0xF7F2F2), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 5);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "BACK\n");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x1D0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_INVERTERSCREEN);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(95));
    lv_obj_set_height(ui_Container1, lv_pct(71));
    lv_obj_set_x(ui_Container1, -2);
    lv_obj_set_y(ui_Container1, -1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x9ECBC2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container1, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_Container1, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 336);
    lv_obj_set_height(ui_Spinner2, 66);
    lv_obj_set_x(ui_Spinner2, -198);
    lv_obj_set_y(ui_Spinner2, -105);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x2A2A31), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Spinner2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -35);
    lv_obj_set_y(ui_Label12, -21);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Total voltage");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltage_value_ = lv_label_create(ui_Spinner2);
    lv_obj_set_width(ui_voltage_value_, lv_pct(54));
    lv_obj_set_height(ui_voltage_value_, lv_pct(50));
    lv_obj_set_x(ui_voltage_value_, 7);
    lv_obj_set_y(ui_voltage_value_, 7);
    lv_obj_set_align(ui_voltage_value_, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_voltage_value_, lv_color_hex(0x000601), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltage_value_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltage_value_, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner3 = lv_spinner_create(ui_Container1, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 336);
    lv_obj_set_height(ui_Spinner3, 66);
    lv_obj_set_x(ui_Spinner3, -199);
    lv_obj_set_y(ui_Spinner3, 107);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0x2A2A31), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Spinner3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -53);
    lv_obj_set_y(ui_Label15, -23);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "SOC");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOC_value = lv_label_create(ui_Spinner3);
    lv_obj_set_width(ui_SOC_value, lv_pct(54));
    lv_obj_set_height(ui_SOC_value, lv_pct(50));
    lv_obj_set_x(ui_SOC_value, 7);
    lv_obj_set_y(ui_SOC_value, 7);
    lv_obj_set_align(ui_SOC_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_SOC_value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner4 = lv_spinner_create(ui_Container1, 1000, 90);
    lv_obj_set_width(ui_Spinner4, 336);
    lv_obj_set_height(ui_Spinner4, 66);
    lv_obj_set_x(ui_Spinner4, 206);
    lv_obj_set_y(ui_Spinner4, 98);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x2A2A31), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Spinner4);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -53);
    lv_obj_set_y(ui_Label17, -23);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "SOH");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOH_value = lv_label_create(ui_Spinner4);
    lv_obj_set_width(ui_SOH_value, lv_pct(54));
    lv_obj_set_height(ui_SOH_value, lv_pct(50));
    lv_obj_set_x(ui_SOH_value, 7);
    lv_obj_set_y(ui_SOH_value, 7);
    lv_obj_set_align(ui_SOH_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_SOH_value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner5 = lv_spinner_create(ui_Container1, 1000, 90);
    lv_obj_set_width(ui_Spinner5, 336);
    lv_obj_set_height(ui_Spinner5, 66);
    lv_obj_set_x(ui_Spinner5, 200);
    lv_obj_set_y(ui_Spinner5, -7);
    lv_obj_set_align(ui_Spinner5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner5, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner5, lv_color_hex(0x2A2A31), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Spinner5);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -41);
    lv_obj_set_y(ui_Label19, -22);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "frequency");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_frequency_value = lv_label_create(ui_Spinner5);
    lv_obj_set_width(ui_frequency_value, lv_pct(54));
    lv_obj_set_height(ui_frequency_value, lv_pct(50));
    lv_obj_set_x(ui_frequency_value, 7);
    lv_obj_set_y(ui_frequency_value, 7);
    lv_obj_set_align(ui_frequency_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_frequency_value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner6 = lv_spinner_create(ui_Container1, 1000, 90);
    lv_obj_set_width(ui_Spinner6, 336);
    lv_obj_set_height(ui_Spinner6, 66);
    lv_obj_set_x(ui_Spinner6, 201);
    lv_obj_set_y(ui_Spinner6, -105);
    lv_obj_set_align(ui_Spinner6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner6, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner6, lv_color_hex(0x2A2A31), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Spinner6);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -53);
    lv_obj_set_y(ui_Label21, -23);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "power");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_value = lv_label_create(ui_Spinner6);
    lv_obj_set_width(ui_power_value, lv_pct(54));
    lv_obj_set_height(ui_power_value, lv_pct(50));
    lv_obj_set_x(ui_power_value, 7);
    lv_obj_set_y(ui_power_value, 7);
    lv_obj_set_align(ui_power_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_power_value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner7 = lv_spinner_create(ui_Container1, 1000, 90);
    lv_obj_set_width(ui_Spinner7, 336);
    lv_obj_set_height(ui_Spinner7, 66);
    lv_obj_set_x(ui_Spinner7, -197);
    lv_obj_set_y(ui_Spinner7, -3);
    lv_obj_set_align(ui_Spinner7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner7, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner7, lv_color_hex(0x2A2A31), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Spinner7);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -35);
    lv_obj_set_y(ui_Label23, -25);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Total current");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_current_value = lv_label_create(ui_Spinner7);
    lv_obj_set_width(ui_current_value, lv_pct(54));
    lv_obj_set_height(ui_current_value, lv_pct(50));
    lv_obj_set_x(ui_current_value, 7);
    lv_obj_set_y(ui_current_value, 7);
    lv_obj_set_align(ui_current_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_current_value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_voltage_value_, ui_event_voltage_value_, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SOC_value, ui_event_SOC_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SOH_value, ui_event_SOH_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_frequency_value, ui_event_frequency_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_power_value, ui_event_power_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_current_value, ui_event_current_value, LV_EVENT_ALL, NULL);
    uic_INVERTERSCREEN = ui_INVERTERSCREEN;
    uic_voltage_value_ = ui_voltage_value_;
    uic_SOC_value = ui_SOC_value;
    uic_SOH_value = ui_SOH_value;
    uic_frequency_value = ui_frequency_value;
    uic_power_value = ui_power_value;
    uic_current_value = ui_current_value;

}

void ui_INVERTERSCREEN_screen_destroy(void)
{
    if(ui_INVERTERSCREEN) lv_obj_del(ui_INVERTERSCREEN);

    // NULL screen variables
    uic_INVERTERSCREEN = NULL;
    ui_INVERTERSCREEN = NULL;
    ui_Label10 = NULL;
    ui_Button7 = NULL;
    ui_Label3 = NULL;
    ui_Container1 = NULL;
    ui_Spinner2 = NULL;
    ui_Label12 = NULL;
    uic_voltage_value_ = NULL;
    ui_voltage_value_ = NULL;
    ui_Spinner3 = NULL;
    ui_Label15 = NULL;
    uic_SOC_value = NULL;
    ui_SOC_value = NULL;
    ui_Spinner4 = NULL;
    ui_Label17 = NULL;
    uic_SOH_value = NULL;
    ui_SOH_value = NULL;
    ui_Spinner5 = NULL;
    ui_Label19 = NULL;
    uic_frequency_value = NULL;
    ui_frequency_value = NULL;
    ui_Spinner6 = NULL;
    ui_Label21 = NULL;
    uic_power_value = NULL;
    ui_power_value = NULL;
    ui_Spinner7 = NULL;
    ui_Label23 = NULL;
    uic_current_value = NULL;
    ui_current_value = NULL;

}
