// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_INVERTERSCREEN_H
#define UI_INVERTERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_INVERTERSCREEN
extern void ui_INVERTERSCREEN_screen_init(void);
extern void ui_INVERTERSCREEN_screen_destroy(void);
extern lv_obj_t * ui_INVERTERSCREEN;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Label12;
extern void ui_event_voltage_value_(lv_event_t * e);
extern lv_obj_t * ui_voltage_value_;
extern lv_obj_t * ui_Spinner3;
extern lv_obj_t * ui_Label15;
extern void ui_event_SOC_value(lv_event_t * e);
extern lv_obj_t * ui_SOC_value;
extern lv_obj_t * ui_Spinner4;
extern lv_obj_t * ui_Label17;
extern void ui_event_SOH_value(lv_event_t * e);
extern lv_obj_t * ui_SOH_value;
extern lv_obj_t * ui_Spinner5;
extern lv_obj_t * ui_Label19;
extern void ui_event_frequency_value(lv_event_t * e);
extern lv_obj_t * ui_frequency_value;
extern lv_obj_t * ui_Spinner6;
extern lv_obj_t * ui_Label21;
extern void ui_event_power_value(lv_event_t * e);
extern lv_obj_t * ui_power_value;
extern lv_obj_t * ui_Spinner7;
extern lv_obj_t * ui_Label23;
extern void ui_event_current_value(lv_event_t * e);
extern lv_obj_t * ui_current_value;
// CUSTOM VARIABLES
extern lv_obj_t * uic_INVERTERSCREEN;
extern lv_obj_t * uic_voltage_value_;
extern lv_obj_t * uic_SOC_value;
extern lv_obj_t * uic_SOH_value;
extern lv_obj_t * uic_frequency_value;
extern lv_obj_t * uic_power_value;
extern lv_obj_t * uic_current_value;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

