// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_current_value__;
lv_obj_t * uic_soc_value__;
lv_obj_t * uic_temp_value;
lv_obj_t * uic_fault_value_;
lv_obj_t * uic_voltage_value__;
lv_obj_t * uic_LIFO_BATTERY_SCREEN;
lv_obj_t * ui_LIFO_BATTERY_SCREEN = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Bar8 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_voltage_value__ = NULL;
lv_obj_t * ui_Colorwheel1 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_Bar2 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_fault_value_ = NULL;
lv_obj_t * ui_Bar3 = NULL;
lv_obj_t * ui_Label56 = NULL;
lv_obj_t * ui_temp_value = NULL;
lv_obj_t * ui_Bar4 = NULL;
lv_obj_t * ui_Label57 = NULL;
lv_obj_t * ui_soc_value__ = NULL;
lv_obj_t * ui_Bar5 = NULL;
lv_obj_t * ui_Label58 = NULL;
lv_obj_t * ui_current_value__ = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions
void ui_event_voltage_value__(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lifo_voltage_value__(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HOME_SCREEN_screen_init);
    }
}

void ui_event_fault_value_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lifo_fault_value_(e);
    }
}

void ui_event_temp_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lifo_temp_value(e);
    }
}

void ui_event_soc_value__(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lifo_soc_value__(e);
    }
}

void ui_event_current_value__(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lifo_current_value__(e);
    }
}

// build funtions

void ui_LIFO_BATTERY_SCREEN_screen_init(void)
{
    ui_LIFO_BATTERY_SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LIFO_BATTERY_SCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LIFO_BATTERY_SCREEN, lv_color_hex(0xF7F3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LIFO_BATTERY_SCREEN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LIFO_BATTERY_SCREEN, lv_color_hex(0x49296F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LIFO_BATTERY_SCREEN, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_LIFO_BATTERY_SCREEN);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 752);
    lv_obj_set_height(ui_Bar1, 84);
    lv_obj_set_x(ui_Bar1, -5);
    lv_obj_set_y(ui_Bar1, -184);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Label52 = lv_label_create(ui_Bar1);
    lv_obj_set_width(ui_Label52, 406);
    lv_obj_set_height(ui_Label52, 41);
    lv_obj_set_x(ui_Label52, 62);
    lv_obj_set_y(ui_Label52, -1);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "LIFOP04 Battery ");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0x0D0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar8 = lv_bar_create(ui_LIFO_BATTERY_SCREEN);
    lv_bar_set_value(ui_Bar8, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar8, 236);
    lv_obj_set_height(ui_Bar8, 129);
    lv_obj_set_x(ui_Bar8, -267);
    lv_obj_set_y(ui_Bar8, -67);
    lv_obj_set_align(ui_Bar8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0x034163), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Bar8);
    lv_obj_set_width(ui_Label53, 117);
    lv_obj_set_height(ui_Label53, 29);
    lv_obj_set_x(ui_Label53, 11);
    lv_obj_set_y(ui_Label53, -37);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "Voltage");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0x030300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltage_value__ = lv_label_create(ui_Bar8);
    lv_obj_set_width(ui_voltage_value__, 150);
    lv_obj_set_height(ui_voltage_value__, 60);
    lv_obj_set_x(ui_voltage_value__, 24);
    lv_obj_set_y(ui_voltage_value__, 11);
    lv_obj_set_align(ui_voltage_value__, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_voltage_value__, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltage_value__, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_voltage_value__, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_voltage_value__, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voltage_value__, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel1 = lv_colorwheel_create(ui_LIFO_BATTERY_SCREEN, true);
    lv_obj_set_width(ui_Colorwheel1, 445);
    lv_obj_set_height(ui_Colorwheel1, 73);
    lv_obj_set_x(ui_Colorwheel1, 35);
    lv_obj_set_y(ui_Colorwheel1, -182);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);

    ui_Button11 = lv_btn_create(ui_LIFO_BATTERY_SCREEN);
    lv_obj_set_width(ui_Button11, 120);
    lv_obj_set_height(ui_Button11, 44);
    lv_obj_set_x(ui_Button11, -324);
    lv_obj_set_y(ui_Button11, 203);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label54 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "Back");
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_LIFO_BATTERY_SCREEN);
    lv_bar_set_value(ui_Bar2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 236);
    lv_obj_set_height(ui_Bar2, 129);
    lv_obj_set_x(ui_Bar2, 137);
    lv_obj_set_y(ui_Bar2, 82);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x034163), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Bar2);
    lv_obj_set_width(ui_Label55, 141);
    lv_obj_set_height(ui_Label55, 29);
    lv_obj_set_x(ui_Label55, 18);
    lv_obj_set_y(ui_Label55, -40);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "Fault status");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0x030300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fault_value_ = lv_label_create(ui_Bar2);
    lv_obj_set_width(ui_fault_value_, 150);
    lv_obj_set_height(ui_fault_value_, 60);
    lv_obj_set_x(ui_fault_value_, 28);
    lv_obj_set_y(ui_fault_value_, 8);
    lv_obj_set_align(ui_fault_value_, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_fault_value_, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fault_value_, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_fault_value_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fault_value_, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fault_value_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_LIFO_BATTERY_SCREEN);
    lv_bar_set_value(ui_Bar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 236);
    lv_obj_set_height(ui_Bar3, 129);
    lv_obj_set_x(ui_Bar3, -156);
    lv_obj_set_y(ui_Bar3, 85);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x034163), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Bar3);
    lv_obj_set_width(ui_Label56, 148);
    lv_obj_set_height(ui_Label56, 17);
    lv_obj_set_x(ui_Label56, 26);
    lv_obj_set_y(ui_Label56, -42);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "Temperature");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0x030300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_value = lv_label_create(ui_Bar3);
    lv_obj_set_width(ui_temp_value, 150);
    lv_obj_set_height(ui_temp_value, 60);
    lv_obj_set_x(ui_temp_value, 23);
    lv_obj_set_y(ui_temp_value, 11);
    lv_obj_set_align(ui_temp_value, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_temp_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp_value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_temp_value, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_temp_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_LIFO_BATTERY_SCREEN);
    lv_bar_set_value(ui_Bar4, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 236);
    lv_obj_set_height(ui_Bar4, 129);
    lv_obj_set_x(ui_Bar4, 250);
    lv_obj_set_y(ui_Bar4, -64);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x034163), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_Bar4);
    lv_obj_set_width(ui_Label57, 117);
    lv_obj_set_height(ui_Label57, 29);
    lv_obj_set_x(ui_Label57, 11);
    lv_obj_set_y(ui_Label57, -37);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "SOC");
    lv_obj_set_style_text_color(ui_Label57, lv_color_hex(0x030300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soc_value__ = lv_label_create(ui_Bar4);
    lv_obj_set_width(ui_soc_value__, 150);
    lv_obj_set_height(ui_soc_value__, 60);
    lv_obj_set_x(ui_soc_value__, 28);
    lv_obj_set_y(ui_soc_value__, 9);
    lv_obj_set_align(ui_soc_value__, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_soc_value__, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soc_value__, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_soc_value__, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_soc_value__, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soc_value__, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar5 = lv_bar_create(ui_LIFO_BATTERY_SCREEN);
    lv_bar_set_value(ui_Bar5, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar5, 236);
    lv_obj_set_height(ui_Bar5, 129);
    lv_obj_set_x(ui_Bar5, 0);
    lv_obj_set_y(ui_Bar5, -57);
    lv_obj_set_align(ui_Bar5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar5, lv_color_hex(0x034163), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Bar5);
    lv_obj_set_width(ui_Label58, 117);
    lv_obj_set_height(ui_Label58, 29);
    lv_obj_set_x(ui_Label58, 11);
    lv_obj_set_y(ui_Label58, -37);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "Current");
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0x030300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_current_value__ = lv_label_create(ui_Bar5);
    lv_obj_set_width(ui_current_value__, 150);
    lv_obj_set_height(ui_current_value__, 60);
    lv_obj_set_x(ui_current_value__, 27);
    lv_obj_set_y(ui_current_value__, 5);
    lv_obj_set_align(ui_current_value__, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_current_value__, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_current_value__, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_current_value__, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_current_value__, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_current_value__, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_LIFO_BATTERY_SCREEN);
    lv_obj_set_width(ui_Switch1, 153);
    lv_obj_set_height(ui_Switch1, 57);
    lv_obj_set_x(ui_Switch1, -1);
    lv_obj_set_y(ui_Switch1, 189);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x5F1508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x9C1515), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x219D09), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Spinner1 = lv_spinner_create(ui_LIFO_BATTERY_SCREEN, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 130);
    lv_obj_set_height(ui_Spinner1, 60);
    lv_obj_set_x(ui_Spinner1, -290);
    lv_obj_set_y(ui_Spinner1, -184);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_Spinner1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Spinner1, lv_color_hex(0x020009), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Spinner1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Spinner1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x063A0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_voltage_value__, ui_event_voltage_value__, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fault_value_, ui_event_fault_value_, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_temp_value, ui_event_temp_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soc_value__, ui_event_soc_value__, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_current_value__, ui_event_current_value__, LV_EVENT_ALL, NULL);
    uic_LIFO_BATTERY_SCREEN = ui_LIFO_BATTERY_SCREEN;
    uic_voltage_value__ = ui_voltage_value__;
    uic_fault_value_ = ui_fault_value_;
    uic_temp_value = ui_Label56;
    uic_temp_value = ui_temp_value;
    uic_soc_value__ = ui_soc_value__;
    uic_current_value__ = ui_current_value__;

}

void ui_LIFO_BATTERY_SCREEN_screen_destroy(void)
{
    if(ui_LIFO_BATTERY_SCREEN) lv_obj_del(ui_LIFO_BATTERY_SCREEN);

    // NULL screen variables
    uic_LIFO_BATTERY_SCREEN = NULL;
    ui_LIFO_BATTERY_SCREEN = NULL;
    ui_Bar1 = NULL;
    ui_Label52 = NULL;
    ui_Bar8 = NULL;
    ui_Label53 = NULL;
    uic_voltage_value__ = NULL;
    ui_voltage_value__ = NULL;
    ui_Colorwheel1 = NULL;
    ui_Button11 = NULL;
    ui_Label54 = NULL;
    ui_Bar2 = NULL;
    ui_Label55 = NULL;
    uic_fault_value_ = NULL;
    ui_fault_value_ = NULL;
    ui_Bar3 = NULL;
    uic_temp_value = NULL;
    ui_Label56 = NULL;
    ui_Bar4 = NULL;
    ui_Label57 = NULL;
    uic_soc_value__ = NULL;
    ui_soc_value__ = NULL;
    ui_Bar5 = NULL;
    ui_Label58 = NULL;
    uic_current_value__ = NULL;
    ui_current_value__ = NULL;
    ui_Switch1 = NULL;
    ui_Spinner1 = NULL;

}
