// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LIFO_BATTERY_SCREEN_H
#define UI_LIFO_BATTERY_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LIFO_BATTERY_SCREEN
extern void ui_LIFO_BATTERY_SCREEN_screen_init(void);
extern void ui_LIFO_BATTERY_SCREEN_screen_destroy(void);
extern lv_obj_t * ui_LIFO_BATTERY_SCREEN;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Bar8;
extern lv_obj_t * ui_Label53;
extern void ui_event_voltage_value__(lv_event_t * e);
extern lv_obj_t * ui_voltage_value__;
extern lv_obj_t * ui_Colorwheel1;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Label55;
extern void ui_event_fault_value_(lv_event_t * e);
extern lv_obj_t * ui_fault_value_;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Label56;
extern void ui_event_temp_value(lv_event_t * e);
extern lv_obj_t * ui_temp_value;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Label57;
extern void ui_event_soc_value__(lv_event_t * e);
extern lv_obj_t * ui_soc_value__;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_Label58;
extern void ui_event_current_value__(lv_event_t * e);
extern lv_obj_t * ui_current_value__;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LIFO_BATTERY_SCREEN;
extern lv_obj_t * uic_voltage_value__;
extern lv_obj_t * uic_fault_value_;
extern lv_obj_t * uic_temp_value;
extern lv_obj_t * uic_temp_value;
extern lv_obj_t * uic_soc_value__;
extern lv_obj_t * uic_current_value__;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

