// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_ev_charferhadline_;
extern void ui_event_ev_arc(lv_event_t * e);
extern lv_obj_t * ui_ev_arc;
extern lv_obj_t * ui_ev_display_arc;
extern lv_obj_t * ui_ev_dsplay_status_;
extern lv_obj_t * ui_power_container_;
extern lv_obj_t * ui_power_label;
extern void ui_event_ev_power_value_(lv_event_t * e);
extern lv_obj_t * ui_ev_power_value_;
extern lv_obj_t * ui_time_container_;
extern lv_obj_t * ui_time_label;
extern void ui_event_ev_time_value(lv_event_t * e);
extern lv_obj_t * ui_ev_time_value;
extern lv_obj_t * ui_start_container;
extern lv_obj_t * ui_ev_start_label;
extern lv_obj_t * ui_ev_start_button;
extern void ui_event_ev_back_button(lv_event_t * e);
extern lv_obj_t * ui_ev_back_button;
extern lv_obj_t * ui_ev_back_label_;
extern lv_obj_t * ui_stop_cantainer_;
extern lv_obj_t * ui_ev_stop_label;
extern lv_obj_t * ui_ev_stop_button;
extern lv_obj_t * ui_ev_spinner;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

