// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ev_data.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ev_charferhadline_ = NULL;
lv_obj_t * ui_ev_arc = NULL;
lv_obj_t * ui_ev_display_arc = NULL;
lv_obj_t * ui_ev_dsplay_status_ = NULL;
lv_obj_t * ui_power_container_ = NULL;
lv_obj_t * ui_power_label = NULL;
lv_obj_t * ui_ev_power_value_ = NULL;
lv_obj_t * ui_time_container_ = NULL;
lv_obj_t * ui_time_label = NULL;
lv_obj_t * ui_ev_time_value = NULL;
lv_obj_t * ui_start_container = NULL;
lv_obj_t * ui_ev_start_label = NULL;
lv_obj_t * ui_ev_start_button = NULL;
lv_obj_t * ui_ev_back_button = NULL;
lv_obj_t * ui_ev_back_label_ = NULL;
lv_obj_t * ui_stop_cantainer_ = NULL;
lv_obj_t * ui_ev_stop_label = NULL;
lv_obj_t * ui_ev_stop_button = NULL;
lv_obj_t * ui_ev_spinner = NULL;

lv_obj_t * uic_ev_power_value_;
lv_obj_t * uic_ev_time_value;
lv_obj_t * uic_ev_display_arc;
lv_obj_t * uic_ev_status;

// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HOME_SCREEN_screen_init);
    }
}

void ui_event_ev_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_ev_display_arc, target, "", "%");
    }
}

void ui_event_ev_power_value_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ev_powervalue(e);
    }
}

void ui_event_ev_time_value(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ev_timevalue(e);
    }
}

void ui_event_ev_back_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HOME_SCREEN_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x01172C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ev_charferhadline_ = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ev_charferhadline_, 661);
    lv_obj_set_height(ui_ev_charferhadline_, 47);
    lv_obj_set_x(ui_ev_charferhadline_, 5);
    lv_obj_set_y(ui_ev_charferhadline_, -203);
    lv_obj_set_align(ui_ev_charferhadline_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_charferhadline_, "EV CHARGER");
    lv_obj_set_style_text_color(ui_ev_charferhadline_, lv_color_hex(0xFCFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_charferhadline_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ev_charferhadline_, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ev_charferhadline_, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ev_charferhadline_, lv_color_hex(0x05CAFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ev_charferhadline_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ev_arc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_ev_arc, 268);
    lv_obj_set_height(ui_ev_arc, 268);
    lv_obj_set_x(ui_ev_arc, 9);
    lv_obj_set_y(ui_ev_arc, 11);
    lv_obj_set_align(ui_ev_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ev_arc, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_ev_arc, 0);
    lv_obj_set_style_arc_width(ui_ev_arc, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ev_arc, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ev_arc, lv_color_hex(0x12D324), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ev_arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ev_arc, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ev_arc, lv_color_hex(0x5CF7C1), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ev_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ev_display_arc = lv_label_create(ui_ev_arc);
    lv_obj_set_width(ui_ev_display_arc, 88);
    lv_obj_set_height(ui_ev_display_arc, 65);
    lv_obj_set_x(ui_ev_display_arc, -1);
    lv_obj_set_y(ui_ev_display_arc, -10);
    lv_obj_set_align(ui_ev_display_arc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_display_arc, "00");
    lv_obj_set_style_text_color(ui_ev_display_arc, lv_color_hex(0x03F819), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_display_arc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ev_display_arc, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ev_display_arc, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ev_dsplay_status_ = lv_label_create(ui_ev_arc);
    lv_obj_set_width(ui_ev_dsplay_status_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ev_dsplay_status_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ev_dsplay_status_, 0);
    lv_obj_set_y(ui_ev_dsplay_status_, 32);
    lv_obj_set_align(ui_ev_dsplay_status_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_dsplay_status_, "CHARGING STATUS");
    lv_obj_set_style_text_color(ui_ev_dsplay_status_, lv_color_hex(0x0CF213), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_dsplay_status_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power_container_ = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_power_container_);
    lv_obj_set_width(ui_power_container_, 164);
    lv_obj_set_height(ui_power_container_, 110);
    lv_obj_set_x(ui_power_container_, -280);
    lv_obj_set_y(ui_power_container_, -88);
    lv_obj_set_align(ui_power_container_, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_power_container_, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power_label = lv_label_create(ui_power_container_);
    lv_obj_set_width(ui_power_label, 113);
    lv_obj_set_height(ui_power_label, lv_pct(21));
    lv_obj_set_x(ui_power_label, -1);
    lv_obj_set_y(ui_power_label, -38);
    lv_obj_set_align(ui_power_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_power_label, "POWER");
    lv_obj_set_style_text_color(ui_power_label, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_power_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_power_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_power_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ev_power_value_ = lv_label_create(ui_power_container_);
    lv_obj_set_width(ui_ev_power_value_, 105);
    lv_obj_set_height(ui_ev_power_value_, 63);
    lv_obj_set_x(ui_ev_power_value_, -4);
    lv_obj_set_y(ui_ev_power_value_, 18);
    lv_obj_set_align(ui_ev_power_value_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_power_value_, "00");
    lv_obj_set_style_text_color(ui_ev_power_value_, lv_color_hex(0x04FE07), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_power_value_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ev_power_value_, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ev_power_value_, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_container_ = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_time_container_);
    lv_obj_set_width(ui_time_container_, 164);
    lv_obj_set_height(ui_time_container_, 110);
    lv_obj_set_x(ui_time_container_, 280);
    lv_obj_set_y(ui_time_container_, -88);
    lv_obj_set_align(ui_time_container_, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_time_container_, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time_label = lv_label_create(ui_time_container_);
    lv_obj_set_width(ui_time_label, 113);
    lv_obj_set_height(ui_time_label, lv_pct(21));
    lv_obj_set_x(ui_time_label, -1);
    lv_obj_set_y(ui_time_label, -38);
    lv_obj_set_align(ui_time_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time_label, "TIME ");
    lv_obj_set_style_text_color(ui_time_label, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ev_time_value = lv_label_create(ui_time_container_);
    lv_obj_set_width(ui_ev_time_value, 105);
    lv_obj_set_height(ui_ev_time_value, 63);
    lv_obj_set_x(ui_ev_time_value, -4);
    lv_obj_set_y(ui_ev_time_value, 18);
    lv_obj_set_align(ui_ev_time_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_time_value, "00");
    lv_obj_set_style_text_color(ui_ev_time_value, lv_color_hex(0x04FE07), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_time_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ev_time_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ev_time_value, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_container = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_start_container);
    lv_obj_set_width(ui_start_container, 164);
    lv_obj_set_height(ui_start_container, 182);
    lv_obj_set_x(ui_start_container, -281);
    lv_obj_set_y(ui_start_container, 65);
    lv_obj_set_align(ui_start_container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_start_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ev_start_label = lv_label_create(ui_start_container);
    lv_obj_set_width(ui_ev_start_label, 150);
    lv_obj_set_height(ui_ev_start_label, lv_pct(21));
    lv_obj_set_x(ui_ev_start_label, -1);
    lv_obj_set_y(ui_ev_start_label, -52);
    lv_obj_set_align(ui_ev_start_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_start_label, "START");
    lv_obj_set_style_text_color(ui_ev_start_label, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_start_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ev_start_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ev_start_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ev_start_button = lv_btn_create(ui_start_container);
    lv_obj_set_width(ui_ev_start_button, 100);
    lv_obj_set_height(ui_ev_start_button, 95);
    lv_obj_set_x(ui_ev_start_button, -1);
    lv_obj_set_y(ui_ev_start_button, 25);
    lv_obj_set_align(ui_ev_start_button, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ev_start_button, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_ev_start_button,
                      LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ev_start_button, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ev_start_button, lv_color_hex(0x39F807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ev_start_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ev_start_button, lv_color_hex(0x03F61E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ev_start_button, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ev_back_button = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ev_back_button, 114);
    lv_obj_set_height(ui_ev_back_button, 38);
    lv_obj_set_x(ui_ev_back_button, -318);
    lv_obj_set_y(ui_ev_back_button, 199);
    lv_obj_set_align(ui_ev_back_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ev_back_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ev_back_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ev_back_label_ = lv_label_create(ui_ev_back_button);
    lv_obj_set_width(ui_ev_back_label_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ev_back_label_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ev_back_label_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_back_label_, "BACK");
    lv_obj_set_style_text_color(ui_ev_back_label_, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_back_label_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stop_cantainer_ = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_stop_cantainer_);
    lv_obj_set_width(ui_stop_cantainer_, 164);
    lv_obj_set_height(ui_stop_cantainer_, 182);
    lv_obj_set_x(ui_stop_cantainer_, 282);
    lv_obj_set_y(ui_stop_cantainer_, 65);
    lv_obj_set_align(ui_stop_cantainer_, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_stop_cantainer_, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ev_stop_label = lv_label_create(ui_stop_cantainer_);
    lv_obj_set_width(ui_ev_stop_label, 150);
    lv_obj_set_height(ui_ev_stop_label, lv_pct(21));
    lv_obj_set_x(ui_ev_stop_label, -1);
    lv_obj_set_y(ui_ev_stop_label, -52);
    lv_obj_set_align(ui_ev_stop_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ev_stop_label, "STOP");
    lv_obj_set_style_text_color(ui_ev_stop_label, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ev_stop_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ev_stop_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ev_stop_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ev_stop_button = lv_btn_create(ui_stop_cantainer_);
    lv_obj_set_width(ui_ev_stop_button, 100);
    lv_obj_set_height(ui_ev_stop_button, 95);
    lv_obj_set_x(ui_ev_stop_button, -1);
    lv_obj_set_y(ui_ev_stop_button, 25);
    lv_obj_set_align(ui_ev_stop_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ev_stop_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ev_stop_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ev_stop_button, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ev_stop_button, lv_color_hex(0xF80606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ev_stop_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ev_stop_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ev_stop_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ev_stop_button, lv_color_hex(0xFB0707), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ev_stop_button, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ev_spinner = lv_spinner_create(ui_Screen2, 1000, 90);
    lv_obj_set_width(ui_ev_spinner, 315);
    lv_obj_set_height(ui_ev_spinner, 317);
    lv_obj_set_x(ui_ev_spinner, 8);
    lv_obj_set_y(ui_ev_spinner, 10);
    lv_obj_set_align(ui_ev_spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ev_spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_ev_spinner, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ev_spinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ev_spinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ev_spinner, lv_color_hex(0xA1E19F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ev_spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ev_spinner, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ev_spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ev_spinner, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ev_spinner, lv_color_hex(0x12EE94), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ev_spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ev_spinner, lv_color_hex(0x4498AF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ev_spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ev_arc, ui_event_ev_arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ev_power_value_, ui_event_ev_power_value_, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ev_time_value, ui_event_ev_time_value, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ev_back_button, ui_event_ev_back_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_ev_start_button, ui_event_ev_start_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ev_stop_button, ui_event_ev_stop_button, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ev_charferhadline_ = NULL;
    ui_ev_arc = NULL;
    ui_ev_display_arc = NULL;
    ui_ev_dsplay_status_ = NULL;
    ui_power_container_ = NULL;
    ui_power_label = NULL;
    ui_ev_power_value_ = NULL;
    ui_time_container_ = NULL;
    ui_time_label = NULL;
    ui_ev_time_value = NULL;
    ui_start_container = NULL;
    ui_ev_start_label = NULL;
    ui_ev_start_button = NULL;
    ui_ev_back_button = NULL;
    ui_ev_back_label_ = NULL;
    ui_stop_cantainer_ = NULL;
    ui_ev_stop_label = NULL;
    ui_ev_stop_button = NULL;
    ui_ev_spinner = NULL;

    uic_ev_power_value_ = ui_ev_power_value_;
uic_ev_time_value   = ui_ev_time_value;
uic_ev_display_arc  = ui_ev_display_arc;
uic_ev_status       = ui_ev_dsplay_status_;

}
