// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

// This file was generated by SquareLine Studio
// Modified for SD image loading (ESP32-S3 7 inch)

#include "ui.h"

/* ================= OBJECTS ================= */
lv_obj_t * ui_SMPS_SCREEN = NULL;
lv_obj_t * ui_Image_SMPS;   // Image object

/* ================= EVENT ================= */
void ui_event_SMPS_SCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&
       lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT)
    {
        lv_indev_wait_release(lv_indev_get_act());

        /* CHANGE SCREEN */
        _ui_screen_change(&ui_HOME_SCREEN, LV_SCR_LOAD_ANIM_FADE_OUT, 0, 0, &ui_HOME_SCREEN_screen_init);

    }
}

/* ================= SCREEN INIT ================= */
void ui_SMPS_SCREEN_screen_init(void)
{
    ui_SMPS_SCREEN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SMPS_SCREEN, LV_OBJ_FLAG_SCROLLABLE);

    /*  CREATE IMAGE OBJECT */
    ui_Image_SMPS = lv_img_create(ui_SMPS_SCREEN);

    /*  FULL SCREEN SIZE */
    lv_obj_set_size(ui_Image_SMPS, 800, 480);
    lv_obj_align(ui_Image_SMPS, LV_ALIGN_CENTER, 0, 0);

    /*  LOAD IMAGE FROM SD */
    lv_img_set_src(ui_Image_SMPS,&ui_img_smpslogo800x400_png);

    /* EVENT */
    lv_obj_add_event_cb(ui_SMPS_SCREEN, ui_event_SMPS_SCREEN, LV_EVENT_ALL, NULL);
}

/* ================= DESTROY ================= */
void ui_SMPS_SCREEN_screen_destroy(void)
{
    if(ui_SMPS_SCREEN)
    {
        lv_obj_del(ui_SMPS_SCREEN);
        ui_SMPS_SCREEN = NULL;
    }
}
