// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SMPS_SCREEN_H
#define UI_SMPS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SMPS_SCREEN
extern void ui_SMPS_SCREEN_screen_init(void);
extern void ui_SMPS_SCREEN_screen_destroy(void);
extern void ui_event_SMPS_SCREEN(lv_event_t * e);
extern lv_obj_t * ui_SMPS_SCREEN;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SMPS_SCREEN;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

